title: "He Yuan"
author: "He Yuan"
description: "PhD student, Umass Amherst"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "home.md", title: "Home", sidebaricon: home}
  - {file: "research.md", title: "Research", sidebaricon: comments}
  - {file: "teaching.md", title: "Teaching", sidebaricon: comments}
  - {file: "talking.md", title: "Talk", sidebaricon: comments} 
  - {file: "reading.md", title: "Reading Group", sidebaricon: comments} 



external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:heyuan@umass.edu"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

defaults:
  - scope:
      path: ""
    values:
      layout: page
      show_title: false
      show_header: false
