title: "He Yuan"
author: "He Yuan"
description: "PhD student in Philosophy,Umass Amherst"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: true             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

#show_frame: "/assets/images/background.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", title: "Home", sidebaricon: home}
  - {file: "publications.md", title: "Publication", sidebaricon: book}
  - {file: "cv.md", title: "CV", sidebaricon: file}
  - {file: "teaching.md", title: "Teaching", sidebaricon: chalkboard-teacher}


external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:heyuan@umass.edu"}
  - {title: PhilPapers, icon: book, url: "https://philpeople.org/profiles/he-yuan"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed
